import BodyText from '../../../../components/BodyText/BodyText';
import TitleText from '../../../../components/TitleText/TitleText';
import InformationIcon from '../../../../icons/InformationIcon';
import './MarketSummary.scss';

const MarketSummary = props => {
  return(
    <div className="market-summary">
      <div className="info-svg-container">
        <InformationIcon/>
      </div>
      <BodyText>
      <span className="gradient">Stake HONEY to receive veHONEY</span>, and vote for new collections to be added as collateral. <span className="gradient">Five new collections</span> will be proposed every week to the DAO. Staking HONEY yields revenue generated by the protocol.
      </BodyText>
      <div className="details-row">
        <div className="detail-container">
          <BodyText>Total HONEY locked</BodyText>
          <TitleText>22, 236, 780</TitleText>
        </div>
        <div className="detail-container">
          <BodyText>APY</BodyText>
          <TitleText>N/A</TitleText>
        </div>
      </div>
    </div>
  )
}

export default MarketSummary;